### ISSUE TITLE
[Bug] oad CLI fails on travis for polyfill.min.js

### ISSUE THREAD

**Issue by vishrutshah** [Azure/openapi-diff#105]
CI: https://travis-ci.org/Azure/azure-rest-api-specs/jobs/289276451#L656

```
module.js:529
    throw err;
    ^
Error: Cannot find module './lib/polyfill.min.js'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/travis/build/Azure/azure-rest-api-specs/node_modules/autorest/app.js:4:1)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
```

**Comment by vladbarosan** [comment]
Solved with PR #104
