### ISSUE TITLE
TypeError issue reported by OAD in CI for azure-rest-api-specs repo

### ISSUE THREAD

**Issue by veronicagg** [Azure/openapi-diff#134]
https://travis-ci.org/Azure/azure-rest-api-specs/jobs/513289560
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined

    at validateString (internal/validators.js:125:11)

    at Object.join (path.js:1147:7)

    at exports.Logger.get [as filepath] (/home/travis/build/Azure/azure-rest-api-specs/node_modules/@azure/oad/dist/lib/util/logging.js:92:39)

    at Object.compare (/home/travis/build/Azure/azure-rest-api-specs/node_modules/@azure/oad/dist/lib/validate.js:26:67)

    at runOad (/home/travis/build/Azure/azure-rest-api-specs/scripts/breaking-change.js:68:26)

    at runScript (/home/travis/build/Azure/azure-rest-api-specs/scripts/breaking-change.js:148:27)

    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by michaeljqzq** [comment]
@sarangan12  Hi Sarangan, I saw this issue was related to CI in travis, now we are using Azure pipelines right? I cannot reproduce this issue. Is it still an issue?
