### ISSUE TITLE
UnhandledPromiseRejectionWarning: Unhandled promise rejection.

### ISSUE THREAD

**Issue by bdghaidi** [Azure/openapi-diff#153]
I'm running oad inside a docker container (definition below) it's throwing the following. Any insights into what might be going wrong?

Note: both files being compared are OpenAPI v2.0

**Dockerfile**

```
FROM node:10
WORKDIR /usr/app/src
COPY src /usr/app/src
RUN npm install
CMD [ "sh" ]
```

**Output**

```# npx oad compare $(pwd)/workdir/customer1_1.json $(pwd)/workdir/customer2_1.json -l silly
silly: Initializing OpenApiDiff class
debug: Initialized OpenApiDiff class with options = { consoleLogLevel: 'silly', logFilepath: undefined, json: true }
silly: compare is being called
silly: processViaAutoRest is being called
debug: swaggerPath = "/usr/app/src/workdir/customer1_1.json"
debug: outputFileName = "old"
silly: autoRestPath is being called
debug: Executing: "/usr/app/src/node_modules/.bin/autorest --input-file=/usr/app/src/workdir/customer1_1.json --output-artifact=swagger-document.json --output-artifact=swagger-document.map --output-file=old --output-folder=/tmp"
silly: processViaAutoRest is being called
debug: swaggerPath = "/usr/app/src/workdir/customer2_1.json"
debug: outputFileName = "new"
silly: autoRestPath is being called
debug: Executing: "/usr/app/src/node_modules/.bin/autorest --input-file=/usr/app/src/workdir/customer2_1.json --output-artifact=swagger-document.json --output-artifact=swagger-document.map --output-file=new --output-folder=/tmp"
Error: (node:78) UnhandledPromiseRejectionWarning: TypeError: volume[member].bind is not a function
    at patchFilesystem (/usr/app/src/node_modules/autorest/dist/static-loader.js:277:43)
    at /usr/app/src/node_modules/autorest/dist/static-loader.js:281:18
    at Object.global.staticloader.undo (/usr/app/src/node_modules/autorest/dist/static-loader.js:163:7)
    at process.exit.n [as exit] (/usr/app/src/node_modules/autorest/dist/static-loader.js:170:27)
    at main (/root/.autorest/@microsoft.azure_autorest-core@2.0.4405/node_modules/@microsoft.azure/autorest-core/dist/app.js:517:21)
(node:78) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:78) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

    at OpenApiDiff.processViaAutoRest (/usr/app/src/node_modules/@azure/oad/dist/lib/validators/openApiDiff.js:159:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by jianyexi** [comment]
It's caused by autorest issue : see https://github.com/Azure/autorest/issues/2921
