### ISSUE TITLE
Error: Unable to find a valid AutoRest core package

### ISSUE THREAD

**Issue by ankuronweb** [Azure/openapi-diff#262]
1. Installed the module locally on macosx
2. node v10.24.1

```Error: Unable to find a valid AutoRest core package '@autorest/core' @ '~2.0.4413'.
Error: Unable to find a valid AutoRest core package '@autorest/core' @ '~2.0.4413'.
    at selectVersion (/Users/anktiwari/.nvm/versions/node/v10.24.1/lib/node_modules/@azure/oad/node_modules/autorest/dist/src_autorest-as-a-service_ts.js:393:23)

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   'node /Users/anktiwari/.nvm/versions/node/v10.24.1/lib/node_modules/@azure/oad/node_modules/autorest/dist/app.js --v2 --input-file=swagger-c.json --output-artifact=swagger-document.json --output-artifact=swagger-document.map --output-file=old --output-folder=/var/folders/mw/kyxpq1hs3xjg1bybxm_cw1lm0000gq/T',
  stdout:
   'AutoRest code generation utility [cli version: 3.6.2; node: v10.24.1]\n(C) 2018 Microsoft Corporation.\nhttps://aka.ms/autorest\ninfo    | AutoRest core version selected from configuration: ~2.0.4413.\nFailure:\n',
  stderr:
   'Error: Unable to find a valid AutoRest core package \'@autorest/core\' @ \'~2.0.4413\'.\nError: Unable to find a valid AutoRest core package \'@autorest/core\' @ \'~2.0.4413\'.\n    at selectVersion (/Users/anktiwari/.nvm/versions/node/v10.24.1/lib/node_modules/@azure/oad/node_modules/autorest/dist/src_autorest-as-a-service_ts.js:393:23)\n' }
```

I even tried installing autorest/core node module globally which was successful but still the same error

**Comment by jianyexi** [comment]
Could you try using node v14 ?
