### ISSUE TITLE
Allowing circular references

### ISSUE THREAD

**Issue by alexandreczg** [Azure/openapi-diff#274]
Is there a way to generate the report allowing for circular dependencies on the parameters?

```
OpenApiDiffErrorImpl [VError]: ReferenceError: Circular $ref pointer found at /builds/#/components/schemas/Content/properties/children/items
    at /usr/local/lib/node_modules/openapi-diff/dist/openapi-diff/spec-differ/diff-finder/json-schema-diff.js:27:15
    at Generator.throw (<anonymous>)
    at rejected (/usr/local/lib/node_modules/openapi-diff/dist/openapi-diff/spec-differ/diff-finder/json-schema-diff.js:6:65) {
  jse_shortmsg: 'ReferenceError: Circular $ref pointer found at /builds/#/components/schemas/Content/properties/children/items',
  jse_info: {},
  code: 'OPENAPI_DIFF_DIFF_ERROR'
}
```

Thank you!

**Comment by afonsojramos** [comment]
@mikeharder is this planned in any way? I can try and give a hand here.

**Comment by mikeharder** [comment]
@afonsojramos: If you submit a pull request (with unit tests), we will review it, and likely merge it, if it solves a real problem with no downside.

**Comment by afonsojramos** [comment]
@mikeharder Sounds good, any guiding advice as to where to look? Have opened a few PRs btw 👀

**Comment by Waidmann** [comment]
Any updates? Makes this tool completely unusable for us.

**Comment by afonsojramos** [comment]
@Waidmann I recommend that you take a look at https://github.com/udamir/api-smart-diff
