### ISSUE TITLE
Migrate off TSLint

### ISSUE THREAD

**Issue by mikeharder** [Azure/openapi-diff#332]
```
$ npm run tslint

> @azure/oad@0.10.8 tslint
> tslint --project tsconfig.json "./src/**/*.ts"

The 'no-unnecessary-initializer' rule threw an error in '/home/mharder/openapi-diff-mh/src/lib/util/utils.ts':
TypeError: DeprecationError: 'originalKeywordKind' has been deprecated since v5.0.0 and can no longer be used. Use 'identifierToKeywordKind(identifier)' instead.
    at /home/mharder/openapi-diff-mh/node_modules/typescript/lib/typescript.js:174085:13
    at IdentifierObject.<anonymous> (/home/mharder/openapi-diff-mh/node_modules/typescript/lib/typescript.js:174115:7)
    at isUndefined (/home/mharder/openapi-diff-mh/node_modules/tslint/lib/rules/noUnnecessaryInitializerRule.js:106:14)
    at checkInitializer (/home/mharder/openapi-diff-mh/node_modules/tslint/lib/rules/noUnnecessaryInitializerRule.js:83:13)
    at cb (/home/mharder/openapi-diff-mh/node_modules/tslint/lib/rules/noUnnecessaryInitializerRule.js:60:21)
    at visitNodes (/home/mharder/openapi-diff-mh/node_modules/typescript/lib/typescript.js:28321:24)
    at forEachChildInVariableDeclarationList (/home/mharder/openapi-diff-mh/node_modules/typescript/lib/typescript.js:28970:18)
    at Object.forEachChild (/home/mharder/openapi-diff-mh/node_modules/typescript/lib/typescript.js:28406:37)
    at cb (/home/mharder/openapi-diff-mh/node_modules/tslint/lib/rules/noUnnecessaryInitializerRule.js:80:12)
    at visitNode2 (/home/mharder/openapi-diff-mh/node_modules/typescript/lib/typescript.js:28313:20)
```

I think we need to migrate off `tslint`, it's no longer being updated.

**Comment by konrad-jamrozik** [comment]
- https://stackoverflow.com/questions/76769634/why-am-i-getting-a-deprecationwarning-originalkeywordkind-deprecated-error
- https://stackoverflow.com/questions/76996326/parsing-error-deprecationerror-originalkeywordkind-has-been-deprecated-since
